### ISSUE TITLE
Random (need some help)

### ISSUE THREAD

**Issue by peepo5** [egorsmkv/fail2ban-scripts#1]
I saw that fail2ban supports ssh, apache, nginx and that lot, but does it support quart (flask)? Thanks.

**Comment by egorsmkv** [comment]
Please, clarify for question with additional information

**Comment by peepo5** [comment]
Does fail2ban support python flask?

**Comment by egorsmkv** [comment]
No, as I know

**Comment by peepo5** [comment]
ok
